PREFIX experts: <http://experts.ucdavis.edu/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ucdrp: <http://experts.ucdavis.edu/schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
  ?person rdf:type ?type;
          rdf:type ucdrp:person;
          ucdrp:role ?role;
           .

  ?role a ?role_type;
        vivo:relatedBy ?grant;
        .

	?grant ucdrp:grantType ?grant_type;
	      rdfs:label ?grant_label;
	     vivo:sponsorAwardId ?award_id;
      vivo:assignedBy ?assigned_by;
      .

  ?assigned_by rdfs:label ?grantor_label;
               .

} WHERE {
  bind("{{uri}}" as ?person)

  ?person rdf:type ?type.

  ?role a ?role_type;
        obo:RO_000052 ?person.

  ?grant a vivo:Grant;
         vivo:relates ?role;
         .
  OPTIONAL {
  	?grant ucdrp:grantType ?grant_type.
  }
  OPTIONAL {
	?grant rdfs:label ?grant_label.
  }
  OPTIONAL {
	?grant vivo:sponsorAwardId ?award_id.
  }
  OPTIONAL {
	  ?grant vivo:assignedBy ?grantor.
    ?grantor a vivo:FundingOrganization;
             rdfs:label ?grantor_label;
             .
  }

}
