PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX cite: <http://citationstyles.org/schema/>
PREFIX cito: <http://purl.org/spar/cito/>
PREFIX experts: <http://experts.ucdavis.edu/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX purl: <http://purl.org/ontology/bibo/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX vivo_inf: <http://vitro.mannlib.cornell.edu/default/vitro-kb-inf>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?publication
WHERE {
  bind ({{username}} as ?author)

  GRAPH ?g {
    ?subject rdf:type vivo:Authorship .
    ?subject vivo:relates ?author .
    ?subject vivo:relates ?publication .
    ?publication rdf:type bibo:AcademicArticle .
  }
}
