PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX cito: <http://purl.org/spar/cito/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX experts: <http://experts.ucdavis.edu/schema#>
PREFIX ucdrp: <http://experts.ucdavis.edu/>

CONSTRUCT {
  ?subject rdf:type ?type .
  ?subject rdf:type experts:person .

  ?subject experts:citation ?publication .
  ?publication rdfs:label ?publicationLabel .
  ?publication experts:publication ?publicationVenueLabel .

  ?publication experts:authors ?citationAuthors .
  ?citationAuthors vivo:rank ?authorRank .
  ?citationAuthors vivo:identifiers ?citationPerson .
} WHERE {

  ?subject rdf:type ?type .

  OPTIONAL {
    ?subject vivo:relatedBy ?authorship .
    ?authorship rdf:type vivo:Authorship .

    ?authorship vivo:relates ?publication .
    ?publication rdf:type bibo:AcademicArticle .
    ?publication rdfs:label ?publicationLabel .

    OPTIONAL {
      ?publication vivo:relatedBy ?citationAuthors .
      ?citationAuthors rdf:type vivo:Authorship .
      ?citationAuthors vivo:relates ?citationPerson .
      ?citationPerson rdf:type ?citationPersonType .

      OPTIONAL {
        ?citationAuthors vivo:rank ?authorRank .
      }
    }
    OPTIONAL {
      ?publication vivo:hasPublicationVenue ?publicationVenue .
      ?publicationVenue rdfs:label ?publicationVenueLabel .
    }
  }
  FILTER(
    ?subject = "{{uri}}" &&
    ?citationPersonType IN (vcard:Individual, vivo:FacultyMember, vivo:NonAcademic, foaf:Person))
}
