PREFIX ucdrp: <http://experts.ucdavis.edu/schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>


SELECT ?publication
WHERE {
  bind ({{username}} as ?author)

  ?subject a vivo:Authorship;
           vivo:relates ?author;
           vivo:relates ?publication;
           .
  ?publication a ucdrp:work;
               .
}
